- name: add apt key
  shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: python pycurl
  apt: package=python-pycurl state=present

- name: add the java repository
  apt_repository: repo=ppa:webupd8team/java state=present

- name: add the jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install the packages
  apt: pkg={{item}} state=present
  with_items:
    - oracle-java7-installer
    - jenkins
